module.exports = {
  env: {
    node: true,
  },
  plugins: ['vue'],
  extends: [
    '@vue/standard',
  ],
  parser: 'vue-eslint-parser',
  parserOptions: {
    ecmaVersion: 2020,
  },
  rules: {
    'arrow-spacing': 'warn',
    'comma-dangle': ['warn', 'always-multiline'],
    'comma-spacing': ['warn'],
    indent: ['warn', 2],
    'key-spacing': ['warn', { beforeColon: false }],
    'keyword-spacing': ['warn'],
    'no-console': 'warn',
    'no-debugger': 'warn',
    'no-empty-pattern': 'warn',
    'no-multi-spaces': 'warn',
    'no-unused-vars': 'warn',
    'object-curly-spacing': ['warn', 'always'],
    'quote-props': ['warn', 'as-needed'],
    quotes: ['warn', 'single'],
    semi: ['warn', 'never'],
    'space-before-blocks': ['warn', 'always'],
    'space-before-function-paren': ['warn', 'always'],
    'space-in-parens': ['warn'],
    'space-infix-ops': 'warn',
    'vue/attributes-order': 'warn',
    'vue/first-attribute-linebreak': ['warn', {
      multiline: 'below',
      singleline: 'ignore',
    }],
    'vue/html-closing-bracket-newline': 'warn',
    'vue/html-closing-bracket-spacing': ['warn'],
    'vue/html-indent': ['warn', 2],
    'vue/html-quotes': ['warn'],
    'vue/html-self-closing': 'warn',
    'vue/max-attributes-per-line': [1, {
      multiline: 1,
      singleline: 3,
    }],
    'vue/multiline-html-element-content-newline': 'warn',
    'vue/mustache-interpolation-spacing': 'warn',
    'vue/no-multi-spaces': ['warn', {
      ignoreProperties: false,
    }],
    'vue/no-spaces-around-equal-signs-in-attribute': ['warn'],
    'vue/order-in-components': 'warn',
    'vue/require-explicit-emits': ['warn'],
    'vue/this-in-template': ['warn'],
  },
}
